name: Update Formula

on:
  repository_dispatch:
    types: [update-aeroswitch-formula, update-argonaut-formula]

jobs:
  update-aeroswitch-formula:
    if: ${{ github.event.action == 'update-aeroswitch-formula' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update aeroswitch formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          ARCHIVE_URL="${{ github.event.client_payload.archive_url }}"
          SHA256="${{ github.event.client_payload.sha256 }}"
          
          # Update the formula file
          sed -i "s|url \".*\"|url \"${ARCHIVE_URL}\"|g" Formula/aeroswitch.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|g" Formula/aeroswitch.rb
          sed -i "s|version \".*\"|version \"${VERSION}\"|g" Formula/aeroswitch.rb
          
          # Also update version in test
          sed -i "s|AeroSwitch v[0-9.]*|AeroSwitch v${VERSION}|g" Formula/aeroswitch.rb
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Update AeroSwitch to v${{ github.event.client_payload.version }}"
          title: "Update AeroSwitch to v${{ github.event.client_payload.version }}"
          body: |
            Automated update to AeroSwitch v${{ github.event.client_payload.version }}
            
            - Version: ${{ github.event.client_payload.version }}
            - Archive URL: ${{ github.event.client_payload.archive_url }}
            - SHA256: ${{ github.event.client_payload.sha256 }}
          branch: update-aeroswitch-v${{ github.event.client_payload.version }}
          delete-branch: true

  update-argonaut-formula:
    if: ${{ github.event.action == 'update-argonaut-formula' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update argonaut formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          
          # Get URLs and SHA256s from payload
          DARWIN_X64_URL="${{ github.event.client_payload.darwin_x64_url }}"
          DARWIN_X64_SHA256="${{ github.event.client_payload.darwin_x64_sha256 }}"
          DARWIN_ARM64_URL="${{ github.event.client_payload.darwin_arm64_url }}"
          DARWIN_ARM64_SHA256="${{ github.event.client_payload.darwin_arm64_sha256 }}"
          LINUX_X64_URL="${{ github.event.client_payload.linux_x64_url }}"
          LINUX_X64_SHA256="${{ github.event.client_payload.linux_x64_sha256 }}"
          LINUX_ARM64_URL="${{ github.event.client_payload.linux_arm64_url }}"
          LINUX_ARM64_SHA256="${{ github.event.client_payload.linux_arm64_sha256 }}"
          
          echo "Updating formula with provided checksums:"
          echo "  Darwin x64: ${DARWIN_X64_SHA256}"
          echo "  Darwin ARM64: ${DARWIN_ARM64_SHA256}"
          echo "  Linux x64: ${LINUX_X64_SHA256}"
          echo "  Linux ARM64: ${LINUX_ARM64_SHA256}"
          
          # Update URLs and SHA256s for each platform/architecture combination
          # macOS Intel
          sed -i "s|url \"https://github.com/darksworm/argonaut/releases/download/.*/argonaut-darwin-x64\"|url \"${DARWIN_X64_URL}\"|g" Formula/argonaut.rb
          sed -i "s|sha256 \"placeholder_darwin_x64_sha256\"|sha256 \"${DARWIN_X64_SHA256}\"|g" Formula/argonaut.rb
          
          # macOS ARM
          sed -i "s|url \"https://github.com/darksworm/argonaut/releases/download/.*/argonaut-darwin-arm64\"|url \"${DARWIN_ARM64_URL}\"|g" Formula/argonaut.rb
          sed -i "s|sha256 \"placeholder_darwin_arm64_sha256\"|sha256 \"${DARWIN_ARM64_SHA256}\"|g" Formula/argonaut.rb
          
          # Linux Intel
          sed -i "s|url \"https://github.com/darksworm/argonaut/releases/download/.*/argonaut-linux-x64\"|url \"${LINUX_X64_URL}\"|g" Formula/argonaut.rb
          sed -i "s|sha256 \"placeholder_linux_x64_sha256\"|sha256 \"${LINUX_X64_SHA256}\"|g" Formula/argonaut.rb
          
          # Linux ARM
          sed -i "s|url \"https://github.com/darksworm/argonaut/releases/download/.*/argonaut-linux-arm64\"|url \"${LINUX_ARM64_URL}\"|g" Formula/argonaut.rb
          sed -i "s|sha256 \"placeholder_linux_arm64_sha256\"|sha256 \"${LINUX_ARM64_SHA256}\"|g" Formula/argonaut.rb
          
          # Update version in test assertion
          sed -i "s|argonaut v[0-9.]*|argonaut v${VERSION}|g" Formula/argonaut.rb
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Update Argonaut to ${{ github.event.client_payload.version }}"
          title: "Update Argonaut to ${{ github.event.client_payload.version }}"
          body: |
            Automated update to Argonaut v${{ github.event.client_payload.version }}
            
            **Binary Information:**
            - **macOS Intel**: ${{ github.event.client_payload.darwin_x64_url }}
              - SHA256: `${{ github.event.client_payload.darwin_x64_sha256 }}`
            - **macOS ARM64**: ${{ github.event.client_payload.darwin_arm64_url }}
              - SHA256: `${{ github.event.client_payload.darwin_arm64_sha256 }}`
            - **Linux Intel**: ${{ github.event.client_payload.linux_x64_url }}
              - SHA256: `${{ github.event.client_payload.linux_x64_sha256 }}`
            - **Linux ARM64**: ${{ github.event.client_payload.linux_arm64_url }}
              - SHA256: `${{ github.event.client_payload.linux_arm64_sha256 }}`
            
            All SHA256 checksums were calculated in the release workflow.
          branch: update-argonaut-${{ github.event.client_payload.version }}
          delete-branch: true
