name: Update Formula

on:
  repository_dispatch:
    types: [update-aeroswitch-formula]

jobs:
  update-aeroswitch-formula:
    if: ${{ github.event.action == 'update-aeroswitch-formula' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update aeroswitch formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          ARCHIVE_URL="${{ github.event.client_payload.archive_url }}"
          SHA256="${{ github.event.client_payload.sha256 }}"
          
          # Update the formula file
          sed -i "s|url \".*\"|url \"${ARCHIVE_URL}\"|g" Formula/aeroswitch.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|g" Formula/aeroswitch.rb
          sed -i "s|version \".*\"|version \"${VERSION}\"|g" Formula/aeroswitch.rb
          
          # Also update version in test
          sed -i "s|AeroSwitch v[0-9.]*|AeroSwitch v${VERSION}|g" Formula/aeroswitch.rb
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Update AeroSwitch to v${{ github.event.client_payload.version }}"
          title: "Update AeroSwitch to v${{ github.event.client_payload.version }}"
          body: |
            Automated update to AeroSwitch v${{ github.event.client_payload.version }}
            
            - Version: ${{ github.event.client_payload.version }}
            - Archive URL: ${{ github.event.client_payload.archive_url }}
            - SHA256: ${{ github.event.client_payload.sha256 }}
          branch: update-aeroswitch-v${{ github.event.client_payload.version }}
          delete-branch: true

